name: Accounts - Check

concurrency:
  group: build-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    branches: [main]
  workflow_dispatch:
    branches: [main]
jobs:
  tests-v10:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
  # build-and-test:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v3
  #     - uses: actions/setup-node@v3
  #       with:
  #         node-version: '14'
  #     - name: install dependencies
  #       run: |-
  #         yarn
  #     - name: Build
  #       run: |-
  #         yarn build
  #     - name: run tests
  #       run: |-
  #         yarn test
  # sonar-cloud:
  #   needs: [build-and-test]
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v3
  #       with:
  #         # Disabling shallow clone is recommended for improving relevancy of reporting
  #         fetch-depth: 0
  #     - name: SonarCloud Scan
  #       uses: sonarsource/sonarcloud-github-action@master
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #         SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  #     - name: SonarQube Quality Gate check
  #       uses: sonarsource/sonarqube-quality-gate-action@master
  #       # Force to fail step after specific time
  #       timeout-minutes: 5
  #       env:
  #         SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  # preview:
  #   needs: [sonar-cloud]
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v3
  #     - uses: amondnet/vercel-action@v20
  #       with:
  #         vercel-token: ${{ secrets.VERCEL_TOKEN }}
  #         github-token: ${{ secrets.GIT_TOKEN }}
  #         vercel-org-id: ${{ secrets.VERCEL_ORG_ID}}
  #         vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID}}
  #         working-directory: ./
  #         alias-domains: pr-{{PR_NUMBER}}-spotify-clone-campaner.vercel.app
  # staging:
  #   needs: [preview]
  #   name: Deploy to staging
  #   environment:
  #     name: preview
  #     url: http://staging-spotify-clone-campaner.vercel.app/
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v3
  #     - uses: actions/setup-node@v3
  #       with:
  #         node-version: '14'
  #     - run: yarn
  #     - run: yarn build
  #     - uses: amondnet/vercel-action@v20
  #       with:
  #         vercel-token: ${{ secrets.VERCEL_TOKEN }}
  #         github-token: ${{ secrets.GIT_TOKEN }}
  #         vercel-org-id: ${{ secrets.VERCEL_ORG_ID}}
  #         vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID}}
  #         working-directory: ./
  #         alias-domains: staging-spotify-clone-campaner.vercel.app
  # deploy:
  #   needs: [staging]
  #   name: Deploy to Prod
  #   environment:
  #     name: production
  #     url: http://potify-clone-campaner.vercel.app/
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - uses: actions/setup-node@v2
  #       with:
  #         node-version: '14'
  #     - run: yarn
  #     - run: yarn build
  #     - uses: amondnet/vercel-action@v20
  #       with:
  #         vercel-token: ${{ secrets.VERCEL_TOKEN }}
  #         github-token: ${{ secrets.GIT_TOKEN }}
  #         vercel-org-id: ${{ secrets.VERCEL_ORG_ID}}
  #         vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID}}
  #         working-directory: ./
  #         alias-domains: spotify-clone-campaner.vercel.app
  #         vercel-args: '--prod'
